name: Create draft release

on:
  workflow_dispatch: # checkov:skip=CKV_GHA_7
    inputs:
      bump-type:
        description: Specify if the version should be bumped as major, minor, patch
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      version-suffix:
        description: "The suffix to apply to the test version e.g. -beta.1, -SNAPSHOT. If not provided defaults to -alpha.{build-number}."
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  SDK_PATH: Sdk/MParticle.Maui.Sdk
  SDK_PROJECT: MParticle.Maui.Sdk
  ROKT_KIT_PATH: Kits/rokt/Sdk/MParticle.Maui.Rokt
  ROKT_KIT_PROJECT: MParticle.Maui.Kits.Rokt

jobs:
  publish-draft-release:
    runs-on: macos-latest
    steps:
      - name: Validate version suffix
        run: |
          if [ -n "${{ github.event.inputs.version-suffix }}" ]; then
            if [[ ! "${{ github.event.inputs.version-suffix }}" =~ ^-[A-Za-z0-9]+([.-][A-Za-z0-9]+)*$ ]]; then
              echo "Error: Invalid version-suffix. It must start with '-' and can include periods or hyphens followed by alphanumeric characters, e.g., '-SNAPSHOT', '-alpha.3'." >&2
              exit 1
            fi
          fi

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1.1.0
        id: login
        with:
          user: rokt

      - name: Setup .NET
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 8.x

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: 16.4

      - name: Install .NET MAUI
        run: dotnet workload install maui

      - name: Get current version
        id: version-file
        run: |
          version_from_file=$(head -n 1 VERSION)
          echo "release-version=$version_from_file" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump-version
        uses: actions-ecosystem/action-bump-semver@34e334551143a5301f38c830e44a22273c6ff5c5 # v1.0.0
        with:
          current_version: ${{ steps.version-file.outputs.release-version }}
          level: ${{ github.event.inputs.bump-type || 'patch' }}

      - name: Save validated version to file
        run: |
          echo "${{ steps.bump-version.outputs.new_version }}" > VERSION

      - name: Release version name
        id: version-suffix
        run: |
          if [ -n "${{ github.event.inputs.version-suffix }}" ]; then
            version_suffix="${{ github.event.inputs.version-suffix }}"
          else
            version_suffix="-alpha.${{ github.run_attempt }}"
          fi
          echo "version-suffix=$version_suffix" >> $GITHUB_OUTPUT

      - name: Export full version with suffix
        id: full-version
        run: |
          full_version="${{ steps.bump-version.outputs.new_version }}${{ steps.version-suffix.outputs.version-suffix }}"
          echo "full-version-with-suffix=$full_version" >> $GITHUB_OUTPUT

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@f62c3c390716df5af712ba5d94f4f4a8efc1306d # v3.1.0
        with:
          tag: ${{ steps.bump-version.outputs.new_version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build SDK
        run: dotnet build ${{ env.SDK_PATH }}/${{ env.SDK_PROJECT }}.csproj -c Release -p:Version=${{ steps.full-version.outputs.full-version-with-suffix }}

      - name: Pack SDK
        run: dotnet pack ${{ env.SDK_PATH }}/${{ env.SDK_PROJECT }}.csproj -c Release -p:Version=${{ steps.full-version.outputs.full-version-with-suffix }}

      - name: Publish to NuGet Test Gallery
        run: dotnet nuget push ${{ env.SDK_PATH }}/bin/Release/${{ env.SDK_PROJECT }}.${{ steps.full-version.outputs.full-version-with-suffix }}.nupkg --source https://apiint.nugettest.org/v3/index.json --api-key ${{steps.login.outputs.NUGET_API_KEY}}

      - name: Build Rokt Kit
        run: dotnet build ${{ env.ROKT_KIT_PATH }}/${{ env.ROKT_KIT_PROJECT }}.csproj -c Release -p:Version=${{ steps.full-version.outputs.full-version-with-suffix }}

      - name: Pack Rokt Kit
        run: dotnet pack ${{ env.ROKT_KIT_PATH }}/${{ env.ROKT_KIT_PROJECT }}.csproj -c Release -p:Version=${{ steps.full-version.outputs.full-version-with-suffix }}

      - name: Publish Rokt Kit to NuGet Test Gallery
        run: dotnet nuget push ${{ env.ROKT_KIT_PATH }}/bin/Release/${{ env.ROKT_KIT_PROJECT }}.${{ steps.full-version.outputs.full-version-with-suffix }}.nupkg --source https://apiint.nugettest.org/v3/index.json --api-key ${{steps.login.outputs.NUGET_API_KEY}}

      - name: Set .csproj version for SDK
        uses: vers-one/dotnet-project-version-updater@6d4de57b8f089d58a00b6ede1f3f05c77bb8e541 # v1.7
        with:
          file: ${{ env.SDK_PATH }}/${{ env.SDK_PROJECT }}.csproj
          version: ${{ steps.bump-version.outputs.new_version }}

      - name: Set .csproj version for Rokt Kit
        uses: vers-one/dotnet-project-version-updater@6d4de57b8f089d58a00b6ede1f3f05c77bb8e541 # v1.7
        with:
          file: ${{ env.ROKT_KIT_PATH }}/${{ env.ROKT_KIT_PROJECT }}.csproj
          version: ${{ steps.bump-version.outputs.new_version }}

      - name: Upload Package Artifact for SDK
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.SDK_PROJECT }}.${{ steps.full-version.outputs.full-version-with-suffix }}.nupkg
          path: ${{ env.SDK_PATH }}/bin/Release/${{ env.SDK_PROJECT }}.${{ steps.full-version.outputs.full-version-with-suffix }}.nupkg

      - name: Upload Package Artifact for Rokt Kit
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.ROKT_KIT_PROJECT }}.${{ steps.full-version.outputs.full-version-with-suffix }}.nupkg
          path: ${{ env.ROKT_KIT_PATH }}/bin/Release/${{ env.ROKT_KIT_PROJECT }}.${{ steps.full-version.outputs.full-version-with-suffix }}.nupkg

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: Create ${{ steps.bump-version.outputs.new_version }}
          branch: release/${{ steps.bump-version.outputs.new_version }}
          title: Prepare release ${{ steps.bump-version.outputs.new_version }}
          add-paths: CHANGELOG.md, VERSION, ${{ env.SDK_PATH }}/${{ env.SDK_PROJECT }}.csproj, ${{ env.ROKT_KIT_PATH }}/${{ env.ROKT_KIT_PROJECT }}.csproj
          base: main
          body: |
            Preparing for release ${{ steps.bump-version.outputs.new_version }}
            - Bumped version
            - Updated changelog
            - Generated test build ${{ steps.full-version.outputs.full-version-with-suffix }}
